### PR TITLE
Add a rudimentary README

### PR DESCRIPTION
**Pull request by TomasHubelbauer**
I instinctively search for the link in the README first and only then fallback to the description so this will save me 333 ms every now and then.

### CODE REVIEW

**Comment by TomasHubelbauer** [comment]
> deployment/now Pending — Now is deploying your app

Should Now be deploying the app off PR branches? 🤔 In this case it doesn't matter though so it's cool.

**Comment by wmhilton** [comment]
> Should Now be deploying the app off PR branches? 🤔 Or does it have a separate instance for all branches for review? The comment above doesn't give any staging URL or anything 🐡

It should! It does! And... hmm Can you not see the CI checks?
image

**Comment by TomasHubelbauer** [comment]
Nope 😢 Only when it was deploying, now I just see the GitHub lines, not the CI contributions

**Comment by TomasHubelbauer** [comment]
(I do now, sorry :-D)

**Pull request merged**
