### PR TITLE
fix: update authentication docs

### PR DESCRIPTION
**Pull request by IAmSSH**
Should fix [this issue](https://github.com/isomorphic-git/isomorphic-git/issues/1749)

This PR updates the Authentication documentation. The content that is covered in other parts of the documentation has been removed and a link to the `onAuth` callback is added.

### CODE REVIEW

**Comment by jcubic** [comment]
I can't merge, I think that Vercel changed what the config file looks like.

**Comment by IAmSSH** [comment]
Oh ok.. Any idea how to resolve this?

**Comment by jcubic** [comment]
No idea, I would use chatGPT to convert the now.json file to vercel alternative and see if it works. Will try to do that.

**Comment by jcubic** [comment]
I've updated the config file according to chatGPT. Please rebase with `source` branch.

**Comment by IAmSSH** [comment]
Done

**Comment by jcubic** [comment]
I'm not sure why but the code was not published. I don't understand there are multiple environments there are GitHub pages and Vercel. I have no idea how to deploy the new website.

**Comment by IAmSSH** [comment]
Yes, I also noticed that.. Will try to see from my side if I can find something

**Comment by jcubic** [comment]
There are more than one branch, there are more recent branches like `main` and `master`.

**Comment by IAmSSH** [comment]
Is it that one of those is getting deployed?

**Comment by jcubic** [comment]
I have no idea

**Pull request merged**
